name: Build and Push Docker Image

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build da imagem
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chatwoot:latest -f .devcontainer/Dockerfile .

      - name: Push da imagem para Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/chatwoot:latest










