name: Build and Push Docker Image

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Construir apenas a imagem base primeiro
      - name: Construir imagem
        run: |
          # Construir a imagem usando seu nome de usuário do Docker Hub
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chatwoot:latest -f docker/Dockerfile .
          
          # Enviar para o Docker Hub
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/chatwoot:latest










